title: Oblast Pir√°ti
baseurl: 
default_locale: "cs"
permalink: pretty
markdown: kramdown
facebookurl: https://www.facebook.com/pages/Pir%C3%A1ti-Praha-6/623900784396150?fref=ts
gems:
  - jekyll-sitemap
  - i18n
paginate: 7
paginate_path: "/clanky/:num/"


# see. best practices DOs and DONTs for details about following section
# http://www.elegantthemes.com/blog/tips-tricks/best-practices-for-using-categories-and-tags-in-wordpress
avail_tags: transparentnost, kultura, sport, web, praha6
avail_cats: AKCE, JEDNANI, CLANKY
avail_filecats: SMLOUVY, ZAPISY, VYKRESY, GRAFIKA
